"""test

Revision ID: 8962c92265d6
Revises: 438647c0dd9e
Create Date: 2023-10-28 17:31:30.657863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8962c92265d6'
down_revision = '438647c0dd9e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
