"""test

Revision ID: 9196b8fc570e
Revises: abfe120062bc
Create Date: 2023-10-28 17:31:55.401413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9196b8fc570e'
down_revision = 'abfe120062bc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
