"""product

Revision ID: a3a03e4b8f46
Revises: f3a93a50cd63
Create Date: 2023-10-28 17:10:48.206462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a03e4b8f46'
down_revision = 'f3a93a50cd63'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('product_index', table_name='product')
    op.create_index('product_index', 'product', ['name'], unique=False, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_index', table_name='product', mysql_length=255)
    op.create_index('product_index', 'product', ['name'], unique=False)
    op.alter_column('product', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
