"""product

Revision ID: 0949a9f243c5
Revises: 109c3bdf7df1
Create Date: 2023-10-28 16:50:10.683452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0949a9f243c5'
down_revision = '109c3bdf7df1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
