"""1

Revision ID: 7ce1ec51674d
Revises: a3a03e4b8f46
Create Date: 2023-10-28 17:29:09.088807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce1ec51674d'
down_revision = 'a3a03e4b8f46'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_index', table_name='product')
    op.create_index('product_index', 'product', ['name'], unique=False, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_index', table_name='product', mysql_length=255)
    op.create_index('product_index', 'product', ['name'], unique=False)
    # ### end Alembic commands ###
