"""price to float

Revision ID: 438647c0dd9e
Revises: 7ce1ec51674d
Create Date: 2023-10-28 17:29:38.484854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438647c0dd9e'
down_revision = '7ce1ec51674d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
